# Site settings
title: "Projeto Kali"
email: "contato@projetokali.com.br"
description: >  # this means to ignore newlines until "baseurl:"
  O KALI é um projeto social, sem fins lucrativos, formado por jovens voluntários que buscam apoiar a realização de sonhos por meio da educação.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

github: "projetokali/projetokali.github.io"
instagram: "projetokali"
facebook: "Kali"
facebook_url: "https://www.facebook.com/projetokali"

form_inscricao_voluntarios: "https://www.google.com/forms/about/"
form_inscricao_alunos: "https://www.google.com/forms/about/"

# Build settings
markdown: kramdown
